Description of writeinfo
Home > sltoolbox > fileio > @sllog > writeinfo.m
writeinfo
PURPOSE
WRITEINFO Writes information to logger without time-stamp
SYNOPSIS
function writeinfo(logger, varargin)
DESCRIPTION
WRITEINFO Writes information to logger without time-stamp
 $ Syntax $
   - writeinfo(logger, ...)
 $ Description $
   - writeinfo(logger, ...). The usage is the same as write, except that
     the time stamp becoming blank during writing.
 $ History $
   - Created by Dahua Lin, on Aug 13, 2006
CROSS-REFERENCE INFORMATION
This function calls:
write WRITE Writes message to a logger
This function is called by:
edl_batchexp EDL_BATCHEXP Performs Batch experiments according to scheme
edl_go EDL_GO The Top interface for doing experiments in EDL
edl_logerror EDL_LOGERROR Logs an error into logger
SOURCE CODE
function writeinfo(logger, varargin)
%WRITEINFO Writes information to logger without time-stamp
%
% $ Syntax $
%   - writeinfo(logger, ...)
%
% $ Description $
%   - writeinfo(logger, ...). The usage is the same as write, except that
%     the time stamp becoming blank during writing.
%
% $ History $
%   - Created by Dahua Lin, on Aug 13, 2006
%
if logger.timestamp
    tstr = datestr(now(), logger.timeformat);
    logger.timeformat = blanks(length(tstr));
    write(logger, varargin{:});
else
    write(logger, varargin{:});
end