Description of writeblank
Home > sltoolbox > fileio > @sllog > writeblank.m
writeblank
PURPOSE
WRITEBLANK Writes a blank line to log
SYNOPSIS
function writeblank(logger)
DESCRIPTION
WRITEBLANK Writes a blank line to log
 $ Syntax $
   - writeblank(logger)
 $ Description $
   - writeblank(logger) writes one blank line to logging output.
 $ History $
   - Created by Dahua Lin, on Aug 13, 2006
CROSS-REFERENCE INFORMATION
This function calls:
disp DISP displays the dataset fields
This function is called by:
edl_batchexp EDL_BATCHEXP Performs Batch experiments according to scheme
edl_go EDL_GO The Top interface for doing experiments in EDL
edl_logerror EDL_LOGERROR Logs an error into logger
SOURCE CODE
function writeblank(logger)
%WRITEBLANK Writes a blank line to log
%
% $ Syntax $
%   - writeblank(logger)
%
% $ Description $
%   - writeblank(logger) writes one blank line to logging output.
%
% $ History $
%   - Created by Dahua Lin, on Aug 13, 2006
%
if logger.winshow
    disp(' ');
end
if ~isempty(logger.files)
    F = logger.files;
    nf = length(F);
    for i = 1 : nf
        if F(i).isactive
            fprintf(F(i).fid, ' \n');
        end
    end
end