Description of sltensor_unfold
Home > sltoolbox > tensor > sltensor_unfold.m
sltensor_unfold
PURPOSE
SLTENSOR_UNFOLD Unfolds a tensor to a matrix
SYNOPSIS
function M = sltensor_unfold(T, k)
DESCRIPTION
SLTENSOR_UNFOLD Unfolds a tensor to a matrix
 $ Syntax $
   - M = sltensor_unfold(T, k)
 $ Arguments $
   - T:        the tensor
   - k:        the dimension along which the tensor is unfolded
   - M:        the matrix obtained by unfolding the tensor
 $ Description $
   - M = sltensor_unfold(T, k) Unfolds a tensor T to the matrix M along
   the k-th dimension.
 $ History $
   - Created by Dahua Lin on Dec 17th, 2005
CROSS-REFERENCE INFORMATION
This function calls:
raise_lackinput RAISE_LACKINPUT Raises an error indicating lack of input argument
This function is called by:
sltensor_multiply SLTENSOR_MULTIPLY Multiplies a tensor and a matrix
sltensor_svd SLTENSOR_SVD Performs a Higher-Order SVD on a Tensor
SOURCE CODE
function M = sltensor_unfold(T, k)
%SLTENSOR_UNFOLD Unfolds a tensor to a matrix
%
% $ Syntax $
%   - M = sltensor_unfold(T, k)
%
% $ Arguments $
%   - T:        the tensor
%   - k:        the dimension along which the tensor is unfolded
%   - M:        the matrix obtained by unfolding the tensor
%
% $ Description $
%   - M = sltensor_unfold(T, k) Unfolds a tensor T to the matrix M along
%   the k-th dimension.
%
% $ History $
%   - Created by Dahua Lin on Dec 17th, 2005
%
%% parse and verify
if nargin < 2
    raise_lackinput('sltensor_unfold', 2);
end
%% compute
n = ndims(T);
if k == 1
    M = T(1:end, :);
elseif k <= n
    if k < n
        pdims = [k, 1:k-1, k+1:n];
    else
        pdims = [k, 1:k-1];
    end
    M = permute(T, pdims);
    M = M(1:end, :);
else
    M = T(:)';
end