Description of display
Home > sltoolbox > ExpDL > @dataset > display.m
display
PURPOSE
DISPLAY displays the dataset fields.
SYNOPSIS
function display(DS)
DESCRIPTION
DISPLAY displays the dataset fields.
CROSS-REFERENCE INFORMATION
This function calls:
disp DISP displays the dataset fields
get GET gets the properties of the dataset
get GET Gets properties of a logger
This function is called by:
SOURCE CODE
function display(DS)
%DISPLAY displays the dataset fields.
if isequal(get(0,'FormatSpacing'),'compact')
    disp([inputname(1) ' =']);
    disp(DS);
else
    disp(' ');
    disp([inputname(1) ' =']);
    disp(' ');
    disp(DS);
end