Description of edl_readctrlfile
Home > sltoolbox > ExpDL > edl_readctrlfile.m
edl_readctrlfile
PURPOSE
EDL_READCTRLFILE Reads in a control file
SYNOPSIS
function C = edl_readctrlfile(filename)
DESCRIPTION
EDL_READCTRLFILE Reads in a control file
 $ Description $
   - C = edl_readctrlfile(filename)
 $ Arguments $
   - filename:     the filename of the control file
   - C:            the struct of the read information
                   - guid:    the GUID string
                   - status:  the n x 1cell array of status
 $ Description $
   - C = edl_readctrlfile(filename) reads in a control file.
 $ History $
   - Created by Dahua Lin, on Aug 14, 2006
CROSS-REFERENCE INFORMATION
This function calls:
edl_check_internalindices EDL_CHECK_INTERNALINDICES Checks the consistency of internal indices
edl_readprops EDL_READPROPS Reads properties from a property table XML file
This function is called by:
edl_batchexp EDL_BATCHEXP Performs Batch experiments according to scheme
edl_updatectrlfile EDL_UPDATECTRLFILE Updates the status in a control file
SOURCE CODE
function C = edl_readctrlfile(filename)
%EDL_READCTRLFILE Reads in a control file
%
% $ Description $
%   - C = edl_readctrlfile(filename)
%
% $ Arguments $
%   - filename:     the filename of the control file
%   - C:            the struct of the read information
%                   - guid:    the GUID string
%                   - status:  the n x 1cell array of status
%
% $ Description $
%   - C = edl_readctrlfile(filename) reads in a control file.
%
% $ History $
%   - Created by Dahua Lin, on Aug 14, 2006
%
%% Read in file
doctag = 'ExpControl';
nodetag = 'Entry';
S = edl_readprops(filename, nodetag);
%% Post-Processing
% doc tag
if ~strcmp(S.tag, doctag)
    error('edl:parseerror', ...
        'Invalid document tag %s for control file', S.tag);
end
% doc attribs
if isempty(S.attribs)
    error('edl:parseerror', ...
        'The document element for control file has no attributes');
end
attrnames = {'guid'};
tf = isfield(S.attribs, attrnames);
if ~all(tf)
    error('edl:parserror', ...
        'The required header %s does not exist', ...
        attrnames{find(~tf, 1)});
end
C.guid = S.attribs.guid;
% entries
edl_check_internalindices(S.(nodetag));
C.status = {S.(nodetag).status};
C.status = C.status(:)';