Description of sladdrowcols
Home > sltoolbox > core > sladdrowcols.m
sladdrowcols
PURPOSE
SLADDROWCOLS Adds the vectors to all rows and all columns
SYNOPSIS
function Y = sladdrowcols(X, vrow, vcol)
DESCRIPTION
SLADDROWCOLS Adds the vectors to all rows and all columns
 $ Syntax $
   - Y = sladdrowcols(X, vrow, vcol)
 $ Arguments $
   - X:            The input matrix
   - vrow:         The row vector to add to all rows
   - vcol:         The column vector to add to all columns
   - Y:            The resultant matrix
 $ Description $
   - Y = sladdrowcols(X, vrow, vcol) adds vrow to all rows of X and
     adds vcol to all columns of Y.
 $ Remarks $
   - The implementation simply wrapps the mex function rowcolop_core.
 $ History $
   - Created by Dahua Lin, on Sep 10, 2006
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
slmetric_pw SLMETRIC_PW Compute the metric between column vectors pairwisely
slcenkernel SLCENKERNEL Compute the centralized kernel matrix
sllocalcoordalign SLLOCALCOORDALIGN Performs optimal local coordinate alignment
SOURCE CODE
function Y = sladdrowcols(X, vrow, vcol)
%SLADDROWCOLS Adds the vectors to all rows and all columns
%
% $ Syntax $
%   - Y = sladdrowcols(X, vrow, vcol)
%
% $ Arguments $
%   - X:            The input matrix
%   - vrow:         The row vector to add to all rows
%   - vcol:         The column vector to add to all columns
%   - Y:            The resultant matrix
%
% $ Description $
%   - Y = sladdrowcols(X, vrow, vcol) adds vrow to all rows of X and
%     adds vcol to all columns of Y.
%
% $ Remarks $
%   - The implementation simply wrapps the mex function rowcolop_core.
%
% $ History $
%   - Created by Dahua Lin, on Sep 10, 2006
%
Y = rowcolop_core(X, vrow, vcol, 1); % 1 is the opcode of addition