Description of slclassify_eucnn
Home > sltoolbox > core > slclassify_eucnn.m
slclassify_eucnn
PURPOSE
SLCLASSIFY_EUCNN Classifies samples using Euclidena-based NN
SYNOPSIS
function labels = slclassify_eucnn(centers, samples)
DESCRIPTION
SLCLASSIFY_EUCNN Classifies samples using Euclidena-based NN
 $ Syntax $
   - labels = slclassify_eucnn(centers, samples)
 $ Arguments $
   - centers:          the class centers
   - samples:          the samples to be classified
   - labels:           the classified result
 $ Description $
   - labels = slclassify_eucnn(centers, samples) classifies the samples to
     nearest centers based on Euclidean distances. The output labels
     indicate which nearest center the samples are classified to.
 $ History $
   - Created by Dahua Lin, on Aug 21, 2006
CROSS-REFERENCE INFORMATION
This function calls:
slmetric_pw SLMETRIC_PW Compute the metric between column vectors pairwisely
slclassify SLCLASSIFY Classifies a set of samples according to final scores
This function is called by:
slgmm SLGMM Learns Gaussian Mixture model from samples
SOURCE CODE
function labels = slclassify_eucnn(centers, samples)
%SLCLASSIFY_EUCNN Classifies samples using Euclidena-based NN
%
% $ Syntax $
%   - labels = slclassify_eucnn(centers, samples)
%
% $ Arguments $
%   - centers:          the class centers
%   - samples:          the samples to be classified
%   - labels:           the classified result
%
% $ Description $
%   - labels = slclassify_eucnn(centers, samples) classifies the samples to
%     nearest centers based on Euclidean distances. The output labels
%     indicate which nearest center the samples are classified to.
%
% $ History $
%   - Created by Dahua Lin, on Aug 21, 2006
%
dists = slmetric_pw(centers, samples, 'eucdist');
labels = slclassify(dists, 1:size(dists,1), 'low');