Description of slmulrowcols
Home > sltoolbox > core > slmulrowcols.m
slmulrowcols
PURPOSE
SLMULROWCOLS Multiplies the vectors to all rows and all columns
SYNOPSIS
function Y = slmulrowcols(X, vrow, vcol)
DESCRIPTION
SLMULROWCOLS Multiplies the vectors to all rows and all columns
 $ Syntax $
   - Y = slmulrowcols(X, vrow, vcol)
 $ Arguments $
   - X:            The input matrix
   - vrow:         The row vector to multiply to all rows
   - vcol:         The column vector to multiply to all columns
   - Y:            The resultant matrix
 $ Description $
   - Y = slmulrowcols(X, vrow, vcol) multiplies vrow to all rows of X and
     adds vcol to all columns of Y.
 $ Remarks $
   - The implementation simply wrapps the mex function rowcolop_core.
 $ History $
   - Created by Dahua Lin, on Sep 10, 2006
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
slmetric_pw SLMETRIC_PW Compute the metric between column vectors pairwisely
slkpca SLPCA Learns a Kernel PCA model from training samples
slgembed SLGEMBED Solves the general graph-based embedding
sllemap SLLEMAP Solves Laplacian Eigenmap Embedding
SOURCE CODE
function Y = slmulrowcols(X, vrow, vcol)
%SLMULROWCOLS Multiplies the vectors to all rows and all columns
%
% $ Syntax $
%   - Y = slmulrowcols(X, vrow, vcol)
%
% $ Arguments $
%   - X:            The input matrix
%   - vrow:         The row vector to multiply to all rows
%   - vcol:         The column vector to multiply to all columns
%   - Y:            The resultant matrix
%
% $ Description $
%   - Y = slmulrowcols(X, vrow, vcol) multiplies vrow to all rows of X and
%     adds vcol to all columns of Y.
%
% $ Remarks $
%   - The implementation simply wrapps the mex function rowcolop_core.
%
% $ History $
%   - Created by Dahua Lin, on Sep 10, 2006
%
Y = rowcolop_core(X, vrow, vcol, 2); % 2 is the opcode of multiplication