
import Crypto 
import Crypto.Random
from Crypto.PublicKey import RSA
from Crypto.Signature import PKCS1_v1_5 
from Crypto.Hash import SHA256
import binascii
import json
from datetime import date

class Wallet:
    def __init__(self):
        random = Crypto.Random.new().read
        self._private_key = RSA.generate(1024,random)
        self._public_key = self._private_key.publickey()
    @property
    def identity(self):
        pubkey = binascii.hexlify(self._public_key.exportKey(format="DER"))
        return pubkey.decode('ascii')

Jimmy = Wallet()
print('Pubkey:',Jimmy.identity)
print('Key Length:', Jimmy.identity.__len__())

SuwandiRL = Wallet()
print('SuwandiRL PubKey:',SuwandiRL.identity)
print('Key Length:', SuwandiRL.identity.__len__())
print("The above program is generated by Suwandi Ryan Loe (student id: 55724681) on", date.today().strftime("%d/%m/%Y %H:%M:%S"))


