Description of incindent
Home > sltoolbox > fileio > @sllog > incindent.m
incindent
PURPOSE
INCINDENT Increases the indent by a specified amount
SYNOPSIS
function logger = incindent(logger, d)
DESCRIPTION
INCINDENT Increases the indent by a specified amount
 $ Syntax $
   - logger = incindent(logger, d)
 $ Arguments $
   - logger:       the target logger
   - d:            the number of levels of indent to be increased
 $ History $
   - Created by Dahua Lin, on Aug 12nd, 2006
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
edl_batchexp EDL_BATCHEXP Performs Batch experiments according to scheme
edl_go EDL_GO The Top interface for doing experiments in EDL
edl_logerror EDL_LOGERROR Logs an error into logger
SOURCE CODE
function logger = incindent(logger, d)
%INCINDENT Increases the indent by a specified amount
%
% $ Syntax $
%   - logger = incindent(logger, d)
%
% $ Arguments $
%   - logger:       the target logger
%   - d:            the number of levels of indent to be increased
%
% $ History $
%   - Created by Dahua Lin, on Aug 12nd, 2006
%
newindent = max(logger.indent + d, 0);
logger.indent = newindent;