Description of slfilepart
Home > sltoolbox > fileio > slfilepart.m
slfilepart
PURPOSE
SLFILEPARTS Extracts a specified part of a file path string
SYNOPSIS
function s = slfilepart(fp, partname)
DESCRIPTION
SLFILEPARTS Extracts a specified part of a file path string
 $ Syntax $
   - s = slfilepart(fp, partname)
 $ Arguments $
   - fp:           the path string
   - partname:     the name of the querying part
   - s:            the string of that part
 $ Description $
   - s = slfilepart(fp, partname) extracts the corresponding part.
     The partname can be either of the following:
       - 'name':   title.ext
       - 'ext':    .ext
       - 'title'   title
       - 'parent'  parent path string
 $ History $
   - Created by Dahua Lin, on Aug 12nd, 2006
CROSS-REFERENCE INFORMATION
This function calls:
raise_lackinput RAISE_LACKINPUT Raises an error indicating lack of input argument
This function is called by:
edl_batchexp EDL_BATCHEXP Performs Batch experiments according to scheme
edl_go EDL_GO The Top interface for doing experiments in EDL
edl_readexpdefs EDL_READEXPDEFS Reads in an experiment definition from XML file
edl_writeprops EDL_WRITEPROPS Writes the property table to XML file
edl_writescript EDL_WRITESCRIPT Writes an EDL script
slpwcomp_blks SLPWCOMP_BLKS Computes pairwise value matrix
SOURCE CODE
function s = slfilepart(fp, partname)
%SLFILEPARTS Extracts a specified part of a file path string
%
% $ Syntax $
%   - s = slfilepart(fp, partname)
%
% $ Arguments $
%   - fp:           the path string
%   - partname:     the name of the querying part
%   - s:            the string of that part
%
% $ Description $
%   - s = slfilepart(fp, partname) extracts the corresponding part.
%     The partname can be either of the following:
%       - 'name':   title.ext
%       - 'ext':    .ext
%       - 'title'   title
%       - 'parent'  parent path string
%
% $ History $
%   - Created by Dahua Lin, on Aug 12nd, 2006
%
if nargin < 2
    raise_lackinput('slfilepart', 2);
end
[p.parent, p.title, p.ext] = fileparts(fp);
switch partname
    case 'name'
        s = [p.title, p.ext];
    case 'ext'
        s = p.ext;
    case 'title'
        s = p.title;
    case 'parent'
        s = p.parent;
    otherwise
        error('sltoolbox:invalidarg', ...
            'Invalid part name for a path: %s', partname);
end