Description of slreadarray
Home > sltoolbox > fileio > slreadarray.m
slreadarray
PURPOSE
SLREADARRAY Reads an array from an array file
SYNOPSIS
function A = slreadarray(filename)
DESCRIPTION
SLREADARRAY Reads an array from an array file
 $ Syntax $
   - A = slreadarray(filename)
 $ Arguments $
   - filename:         the filename of the array file
   - A:                the array read
 $ Description $
   - A = slreadarray(filename) reads an array from an array file and
     returns it by A.
 $ History $
   - Created by Dahua Lin, on Jul 26th, 2006
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
slsumstat_blks SLSUMSTAT_BLKS Sums up statistics on all blocks for partitioned data
slverifyroc_blks SLVERIFYROC_BLKS Computes the verification ROC for blockwise score matrix
sl2dmatcov SL2DMATCOV Computes the 2D matrix-covariances
sl2dpca_apply SL2DPCA_APPLY Applies 2D PCA onto a set of matrices to extract features
sl2dpcaex SL2DPCAEX Learns Extended 2D PCA on a set of matrix samples
slarrmean SLARRMEAN Computes the mean of a set of arrays
slpartitionpca SLPARTITIONPCA Performs Partition-based PCA and saves the models
slpartitionpca_apply SLPARTITIONPCA_APPLY applies partition-based PCA to a set of arrays
slpartitionpca_construct SLPARTITIONPCA_CONSTRUCT Constructs the array from features
slclassify_blks SLCLASSIFY_BLKS Classifies samples according to blockwise scores
SOURCE CODE
function A = slreadarray(filename)
%SLREADARRAY Reads an array from an array file
%
% $ Syntax $
%   - A = slreadarray(filename)
%
% $ Arguments $
%   - filename:         the filename of the array file
%   - A:                the array read
%
% $ Description $
%   - A = slreadarray(filename) reads an array from an array file and
%     returns it by A.
%
% $ History $
%   - Created by Dahua Lin, on Jul 26th, 2006
%
value_types = { ...
    'double', ...
    'single', ...
    'logical', ...
    'char', ...
    'int8', ...
    'uint8', ...
    'int16', ...
    'uint16', ...
    'int32', ...
    'uint32', ...
    'int64', ...
    'uint64'};
%% open file
fid = fopen(filename, 'r');
if fid <= 0
    error('sltoolbox:filefail', ...
        'Fail to open file %s', filename);
end
%% read header
% read and verify tag
tag = fread(fid, 4, '*char')';
if ~isequal(tag, ['arr', 0])
    error('sltoolbox:parseerror', ...
        'The file tag is invalid');
end
% read the value type
typeidx = fread(fid, 1, 'uint8');
valtype = value_types{typeidx};
% read the dimension
d = fread(fid, 1, 'uint8');
%% read size
fseek(fid, 8, -1);
siz = fread(fid, d, 'uint32')';
%% read data
A = fread(fid, prod(siz), ['*', valtype]);
if length(siz) == 1
    siz = [siz, 1];
end
A = reshape(A, siz);
%% close file
fclose(fid);