Description of sledgeset2adjlist
Home > sltoolbox > graph > sledgeset2adjlist.m
sledgeset2adjlist
PURPOSE
SLEDGESET2ADJLIST Converts edge set to adjacency list
SYNOPSIS
function targets = sledgeset2adjlist(n, edges, sch)
DESCRIPTION
SLEDGESET2ADJLIST Converts edge set to adjacency list
 $ Syntax $
   - targets = sledgeset2adjlist(n, edges, sch)
 $ Arguments $
   - n:        The number of (source) nodes
   - edges:    The set of edges (nedges x 2 or nedges x 3)
   - sch:      The id of scheme of conversion to take
               - 0:    no value -> no value
               - 1:    no value -> has value
               - 2:    has value -> no value
               - 3:    has value -> has value
   - targets:  The cell array of targets in adj list
 $ Remarks $
   - an internal function for graph representation conversion.
     no checking of input arguments would be performed.
 $ History $
   - Created by Dahua Lin, on Sep 9, 2006
CROSS-REFERENCE INFORMATION
This function calls:
slcount SLCOUNT Count the number of sum entities
slnums2bounds SLNUMS2BOUNDS Compute the index-boundaries from section sizes
This function is called by:
sladjlist SLADJLIST Construct the adjacency list representation of a graph
SOURCE CODE
function targets = sledgeset2adjlist(n, edges, sch)
%SLEDGESET2ADJLIST Converts edge set to adjacency list
%
% $ Syntax $
%   - targets = sledgeset2adjlist(n, edges, sch)
%
% $ Arguments $
%   - n:        The number of (source) nodes
%   - edges:    The set of edges (nedges x 2 or nedges x 3)
%   - sch:      The id of scheme of conversion to take
%               - 0:    no value -> no value
%               - 1:    no value -> has value
%               - 2:    has value -> no value
%               - 3:    has value -> has value
%   - targets:  The cell array of targets in adj list
%
% $ Remarks $
%   - an internal function for graph representation conversion.
%     no checking of input arguments would be performed.
%
% $ History $
%   - Created by Dahua Lin, on Sep 9, 2006
%
%% prepare storage
targets = cell(n, 1);
%% sort edges
I = edges(:, 1);
J = edges(:, 2);
[I, si] = sort(I);
J = J(si);
if sch == 3
    V = edges(si, 3);
elseif sch == 1
    nedges = length(I);
    V = ones(nedges, 1);
end
%% group targets
nums = slcount(I);
ni = length(nums);
[spos, epos] = slnums2bounds(nums);
if sch == 1 || sch == 3
    for i = 1 : ni
        s = spos(i); e = epos(i);
        if s <= e
            targets{I(s)} = [J(s:e), V(s:e)];
        end
    end
else
    for i = 1 : ni
        s = spos(i); e = epos(i);
        if s <= e
            targets{I(s)} = J(s:e);
        end
    end
end