Description of sladdvec
Home > sltoolbox > core > sladdvec.m
sladdvec
PURPOSE
SLADDVEC adds a vector to columns or rows of a matrix
SYNOPSIS
function Y = sladdvec(X, v, d)
DESCRIPTION
SLADDVEC adds a vector to columns or rows of a matrix
 $ Syntax $
   - Y = sladdvec(X, v, d)
   - Y = sladdvec(X, v)
 $ Arguments $
   - X:        The original matrix
   - v:        The addend vector
   - d:        The dimension along which the vector is to add
   - Y:        The resultant matrix
 $ Description $
   - Y = sladdvec(X, v, d) selects the most efficienct way to add a
     vector v to every column/row of X. If d == 1, then v should be
     a column vector, and is added to each column of X, if d == 2,
     then v should be a row vector, and is added to each row of X.
   - Y = sladdvec(X, v) will automatically determine d according to
     the shape of v.
 $ Remarks $
   - The implementation simply wraps the mex function vecop_core.
 $ History $
   - Created by Dahua Lin, on Sep 10, 2006
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
sldistmean SLDISTMEAN Uses fast method to compute means of pairwise distances
slhistmetric_pw SLHISTMETRIC_PW Computes distance metrics between histograms pairwisely
slimginterp SLIMGINTERP Performs image based interpolation
slpixneighbors SLPIXNEIGHBORS Extracts the neighborhood of pixels from an image
sllocalcoordalign SLLOCALCOORDALIGN Performs optimal local coordinate alignment
sllocaltancoords SLLOCALTANCOORDS Computes the local tangent coordinates
sllocaltanspace SLLOCALTANSPACE Solves the local tangent spaces
sllogistreg SLLOGISTREG Performs Multivariate Logistic Regression
slcov SLCOV Compute the covariance matrix
slgaussest SLGAUSSEST Estimates the Gaussian models from samples
slgausspdf SLGAUSSPDF Computes the probability density of Gaussian models
slgaussrnd SLGAUSSRND Generates random samples from Gaussian models
slposteriori SLPOSTERIORI Computes the posterioris
slposterioritrue SLPOSTERIORITRUE Computes the posteriori that samples belong to true class
slapplypca SLAPPLYPCA Applies PCA model to samples
slcopca SLCOPCA Performs Coupled PCA Learning
slfld SLFLD Performs Fisher Linear Discriminant Analysis
slnlda SLNLDA Performs Nullspace-based Linear Discriminant Analysis
slpca SLPCA Learns a PCA model from training samples
slpcarecon SLPCARECON Reconstructs the samples in original space
slpartitionpca SLPARTITIONPCA Performs Partition-based PCA and saves the models
slpartitionpca_apply SLPARTITIONPCA_APPLY applies partition-based PCA to a set of arrays
slpartitionpca_construct SLPARTITIONPCA_CONSTRUCT Constructs the array from features
sldrawellipse SLDRAWELLIPSE Draws an ellipse on current axis
SOURCE CODE
function Y = sladdvec(X, v, d)
%SLADDVEC adds a vector to columns or rows of a matrix
%
% $ Syntax $
%   - Y = sladdvec(X, v, d)
%   - Y = sladdvec(X, v)
%
% $ Arguments $
%   - X:        The original matrix
%   - v:        The addend vector
%   - d:        The dimension along which the vector is to add
%   - Y:        The resultant matrix
%
% $ Description $
%   - Y = sladdvec(X, v, d) selects the most efficienct way to add a
%     vector v to every column/row of X. If d == 1, then v should be
%     a column vector, and is added to each column of X, if d == 2,
%     then v should be a row vector, and is added to each row of X.
%
%   - Y = sladdvec(X, v) will automatically determine d according to
%     the shape of v.
%
% $ Remarks $
%   - The implementation simply wraps the mex function vecop_core.
%
% $ History $
%   - Created by Dahua Lin, on Sep 10, 2006
%
if nargin < 3
    if size(v, 2) == 1
        d = 1;
    else
        d = 2;
    end
end
Y = vecop_core(X, v, d, 1);  % 1 is the opcode of addition in vecop_core