Description of edl_writeprops
Home > sltoolbox > ExpDL > edl_writeprops.m
edl_writeprops
PURPOSE
EDL_WRITEPROPS Writes the property table to XML file
SYNOPSIS
function edl_writeprops(doctag, attribs, nodeTag, props, filename)
DESCRIPTION
EDL_WRITEPROPS Writes the property table to XML file
 $ Syntax $
   - edl_writeprops(doctag, attribs, nodeTag, props, filename)
 $ Arguments $
   - doctag:       the tag name of document node
   - attribs:      the header attributes
   - nodeTag:      the tag name of child nodes
   - props:        the struct array of all properties
   - filename:     the name of the XML file to be written to
 $ Description $
   - edl_writeprops(doctag, attribs, nodeTag, props, filename) writes
     a table of properties to an XML property table file, with the
     header attributes.
 $ Remarks $
   - For numeric values, they will be converted to string using num2str.
 $ History $
   - Created by Dahua Lin, on Aug 10th, 2006
   - Modified by Dahua Lin, on Aug 13rd, 2006
       - adds support of document header attribute
       - changes the structure of the result
       - adds the selection of node tag
CROSS-REFERENCE INFORMATION
This function calls:
slfilepart SLFILEPARTS Extracts a specified part of a file path string
slmkdir SLMKDIR Makes a directory if it does not exist
raise_lackinput RAISE_LACKINPUT Raises an error indicating lack of input argument
xml_addattribs XML_ADDATTRIBS Adds attributes to an element
This function is called by:
edl_initctrlfile EDL_INITCTRLFILE Creates an initial control file
edl_updatectrlfile EDL_UPDATECTRLFILE Updates the status in a control file
edl_writereport EDL_WRITEREPORT Writes an EDL report
edl_writescript EDL_WRITESCRIPT Writes an EDL script
SOURCE CODE
function edl_writeprops(doctag, attribs, nodeTag, props, filename)
%EDL_WRITEPROPS Writes the property table to XML file
%
% $ Syntax $
%   - edl_writeprops(doctag, attribs, nodeTag, props, filename)
%
% $ Arguments $
%   - doctag:       the tag name of document node
%   - attribs:      the header attributes
%   - nodeTag:      the tag name of child nodes
%   - props:        the struct array of all properties
%   - filename:     the name of the XML file to be written to
%
% $ Description $
%   - edl_writeprops(doctag, attribs, nodeTag, props, filename) writes
%     a table of properties to an XML property table file, with the
%     header attributes.
%
% $ Remarks $
%   - For numeric values, they will be converted to string using num2str.
%
% $ History $
%   - Created by Dahua Lin, on Aug 10th, 2006
%   - Modified by Dahua Lin, on Aug 13rd, 2006
%       - adds support of document header attribute
%       - changes the structure of the result
%       - adds the selection of node tag
import com.mathworks.xml.*;
%% parse and verify input arguments
if nargin < 5
    raise_lackinput('edl_writeprops', 5);
end
if ~isstruct(props)
    error('sltoolbox:invalidarg', ...
        'props should be a struct array');
end
%% Write file
% create document
xdoc = XMLUtils.createDocument(doctag);
xdoc.setVersion('1.0');
xdoc.setEncoding('UTF-8');
docelem = xdoc.getDocumentElement;
% write header
docelem = xml_addattribs(docelem, attribs);
% add elements
n = numel(props);
fns = fieldnames(props);
cf = length(fns);
for i = 1 : n
    propelem = xdoc.createElement(nodeTag);
    cur = props(i);
    for j = 1 : cf
        fn = fns{j};
        val = cur.(fn);
        if isnumeric(val)
            val = num2str(val);
        end
        propelem.setAttribute(fn, val);
    end
    docelem.appendChild(propelem);
end
% write to file
filedir = slfilepart(filename, 'parent');
slmkdir(filedir);
xmlwrite(filename, xdoc);