Description of edl_check_internalindices
Home > sltoolbox > ExpDL > edl_check_internalindices.m
edl_check_internalindices
PURPOSE
EDL_CHECK_INTERNALINDICES Checks the consistency of internal indices
SYNOPSIS
function cprops = edl_check_internalindices(props)
DESCRIPTION
EDL_CHECK_INTERNALINDICES Checks the consistency of internal indices
 $ Syntax $
   - cprops = edl_check_internalindices(props)
 $ Arguments $
   - props:        the struct array of property entries
   - cprops:       the converted array with all indices coverted to
                   numeric
 $ History $
   - Created by Dahua Lin, on Aug 14, 2006
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
edl_readctrlfile EDL_READCTRLFILE Reads in a control file
edl_readreport EDL_READREPORT Reads in a EDL report
edl_readscript EDL_READSCRIPT Reads in a EDL script
SOURCE CODE
function cprops = edl_check_internalindices(props)
%EDL_CHECK_INTERNALINDICES Checks the consistency of internal indices
%
% $ Syntax $
%   - cprops = edl_check_internalindices(props)
%
% $ Arguments $
%   - props:        the struct array of property entries
%   - cprops:       the converted array with all indices coverted to
%                   numeric
%
% $ History $
%   - Created by Dahua Lin, on Aug 14, 2006
%
cprops = props;
if ~isempty(props)
    n = length(props);
    if ~isfield(props, 'internal_index')
        error('edl:parseerror', ...
            'The entries do not have the required field: internal_index');
    end
    for i = 1 : n
        curidx = str2double(props(i).internal_index);
        if curidx ~= i
            error('edl:parseerror', ...
                'Internal index inconsistency');
        end
        cprops(i).internal_index = curidx;
    end
end