Description of raise_lackinput
Home > sltoolbox > utils > raise_lackinput.m
raise_lackinput
PURPOSE
RAISE_LACKINPUT Raises an error indicating lack of input argument
SYNOPSIS
function raise_lackinput(funcname, nmin)
DESCRIPTION
RAISE_LACKINPUT Raises an error indicating lack of input argument
 $ Syntax $
   - raise_lackinput(funcname, nmin)
 $ Arguments $
   - funcname:         the name of invoking function
   - nmin:             the minimum number of input arguments
 $ Description $
   - raise_lackinput(funcname, nmin) raises an error message indicating
     that the number of arguments input to the function specified by
     funcname is not enough. (It should be at least nmin)
 $ History $
   - Created by Dahua Lin on Nov 18th, 2005
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
edl_batchexp EDL_BATCHEXP Performs Batch experiments according to scheme
edl_go EDL_GO The Top interface for doing experiments in EDL
edl_initctrlfile EDL_INITCTRLFILE Creates an initial control file
edl_logerror EDL_LOGERROR Logs an error into logger
edl_readprops EDL_READPROPS Reads properties from a property table XML file
edl_updatectrlfile EDL_UPDATECTRLFILE Updates the status in a control file
edl_writeprops EDL_WRITEPROPS Writes the property table to XML file
edl_writereport EDL_WRITEREPORT Writes an EDL report
edl_writescript EDL_WRITESCRIPT Writes an EDL script
slkmeansex SLKMEANSEX Performs Generalized K-means
sladd SLADD Add a sub-array along some dimensions to an array
slconfine SLCONFINE Confines the values in a range
sldiscrep SLDISCREP Evaluates the discrepancy of two arrays
sldistmean SLDISTMEAN Uses fast method to compute means of pairwise distances
slenforce SLENFORCE Enforce some property on the array A
sllabeledsum SLLABELEDSUM Sums the numbers according to labels
slmetric_cp SLMETRIC_CP Computes the metrics between corresponding pairs of samples
slmetric_pw SLMETRIC_PW Compute the metric between column vectors pairwisely
slmetric_pw_blks SLMETRIC_PW_BLKS Compute the pairwise metrics in a blockwise manner
slmul SLMUL Multiply a sub-array along some dimensions to an array
slpwcalc SLPWCALC Calculates a table pairwisely on two set of scalars
slpwcomp_blks SLPWCOMP_BLKS Computes pairwise value matrix
slpweval SLPWEVAL Perform pairwise computation
slsumstat_blks SLSUMSTAT_BLKS Sums up statistics on all blocks for partitioned data
slsymgeig SLSYMGEIG Solve the generalized eigen decomposition for symmetric matrices
slcountvote SLCOUNTRULE Counts the votings to make histogram
slhistmetric_cp SLHISTMETRIC_CP Computes the metrics between corresponding pairs of histograms
slhistmetric_pw SLHISTMETRIC_PW Computes distance metrics between histograms pairwisely
slvechist SLVECHIST Makes the histogram on prototype vectors by voting
slvote SLVOTE Builds histogram by voting (or fuzzy voting)
slfilepart SLFILEPARTS Extracts a specified part of a file path string
slimgsetprep SLIMGSETPREP organizes the images in a MATLAB friendly way
slaffinitymat SLAFFINITYMAT Constructs an affinity matrix
sledges2adjmat SLEDGES2ADJMAT Creates an adjacency matrix from edge set
slfindnn SLFINDNN Finds the nearest neighbors using specified strategy
slnngraph SLNNGRAPH Constructs a nearest neighborhood based graph
slpruneedgeset SLPRUNEEDGESET Prunes the edge set
slpwgraph SLVALGRAPH Constructs a graph by computing values between nodes pairwisely
slapplyfilterband SLAPPLYFILTERBAND Applies filter band to filter images in batch
slcalcpadsize SLCALCPADSIZE Calculates the size of padding
slimginterp SLIMGINTERP Performs image based interpolation
slpadimg SLPADIMG Pads an image with boundary
slpixneighbors SLPIXNEIGHBORS Extracts the neighborhood of pixels from an image
slresizeimg SLRESIZEIMG Resizes the images by interpolation
slgda SLGDA Performs Baudat's Generalized Discriminant Analysis
slkernelfea SLKERNELFEA Extracts kernelized mapped features
slkernelscatter SLKERNELSCATTER Compute the kernelized scatter matrix
slkfd SLKFD Perform Kernelized Fisher Discriminant Analysis
sliterproc SLITERPROC Runs a general iterative process
slproglearn SLPROGLEARN Performs Progressive Learning from sample source
slreevallearn SLREEVALLEARN Performs an iterative learning based on re-evaluation
slcmds SLMDS Performs Classical Multidimensional scaling
slgembed SLGEMBED Solves the general graph-based embedding
slisomap SLISOMAP Performs ISOMAP manifold embedding
slkernelembed SLKERNELEMBED Finds an embedding space to preserve inner products
sllemap SLLEMAP Solves Laplacian Eigenmap Embedding
sllle SLLLE Performs Locally Linear Embedding
sllle_wg SLLLE_WG Solves the Locally Linear Embedding from weight graph
sllocalcoordalign SLLOCALCOORDALIGN Performs optimal local coordinate alignment
sllocaltancoords SLLOCALTANCOORDS Computes the local tangent coordinates
slnbreconweights SLNBRECONWEIGHTS Solve the optimal reconstruction weights on given neighbors
slcorrectrate SLCORRECTRATE Computes the correct rate of classification
slcorrectrate_blks SLCORRECTRATE_BLKS Computes the correct rate based on blockwise scores
slcumuscore SLCUMUSCORE Computes the cumulative score on multi-class classification
slgetroc SLGETROC Computes some point from ROC Curve
slhistroc SLHISTROC Computes the ROC curve from value histogram
slroc SLROC Computes the ROC
slverifyroc SLVERIFYROC Computes the verification ROC
slverifyroc_blks SLVERIFYROC_BLKS Computes the verification ROC for blockwise score matrix
sllinreg SLLINREG Performs Multivariate Linear Regression and Ridge Regression
sllinrega SLLINREGA Performs Augmented Multivariate Linear Regression
sllogistreg SLLOGISTREG Performs Multivariate Logistic Regression
slcovlarge SLCOVLARGE Computes large covariance matrix using memory-efficient way
slgaussinv SLGAUSSINV Computes the inverse of variance/covariance in Gaussian model
slgaussmdist SLGAUSSMDIST Computes the Malanobis distance between samples and centers
slgausspdf SLGAUSSPDF Computes the probability density of Gaussian models
slposterioritrue SLPOSTERIORITRUE Computes the posteriori that samples belong to true class
slapplypca SLAPPLYPCA Applies PCA model to samples
slcopca SLCOPCA Performs Coupled PCA Learning
sldlda SLDLDA Performs Direct Linear Discriminant Analysis
slfld SLFLD Performs Fisher Linear Discriminant Analysis
slgbfe SLGBFE Performs Graph-based Feature Extraction Learning
sllda SLLDA Trains a Linear Discriminant Model using specified method
slnlda SLNLDA Performs Nullspace-based Linear Discriminant Analysis
slpcareduce SLPCAREDUCE Reduces a PCA model to lower dimension
slscatter SLSCATTER Compute the scatter matrix
sl2dmatcov SL2DMATCOV Computes the 2D matrix-covariances
sl2dpca_apply SL2DPCA_APPLY Applies 2D PCA onto a set of matrices to extract features
sl2dpcaex SL2DPCAEX Learns Extended 2D PCA on a set of matrix samples
slarrmean SLARRMEAN Computes the mean of a set of arrays
slpartitionpca SLPARTITIONPCA Performs Partition-based PCA and saves the models
slpartitionpca_apply SLPARTITIONPCA_APPLY applies partition-based PCA to a set of arrays
slpartitionpca_construct SLPARTITIONPCA_CONSTRUCT Constructs the array from features
sltensor_fold SLTENSOR_FOLD Folds a matrix into a tensor
sltensor_multiply SLTENSOR_MULTIPLY Multiplies a tensor and a matrix
sltensor_unfold SLTENSOR_UNFOLD Unfolds a tensor to a matrix
slfiltertext SLFILTERTEXT Processes the lines of text
sladdpath SLADDPATH Adds dirpath to precede the filenames
slclassify SLCLASSIFY Classifies a set of samples according to final scores
slclassify_blks SLCLASSIFY_BLKS Classifies samples according to blockwise scores
slpartition SLPARTITION Partition a range into blocks in a specified manner
sldrawellipse SLDRAWELLIPSE Draws an ellipse on current axis
sldrawgraph SLDRAWGRAPH Draws a graph
sldrawlabeledpts SLDRAWLABELEDPTS Draws Labeled 2D or 3D points
sldrawmultiellipse SLDRAWMULTIELLIPSE Draws multiple ellipses on axies
SOURCE CODE
function raise_lackinput(funcname, nmin)
%RAISE_LACKINPUT Raises an error indicating lack of input argument
%
% $ Syntax $
%   - raise_lackinput(funcname, nmin)
%
% $ Arguments $
%   - funcname:         the name of invoking function
%   - nmin:             the minimum number of input arguments
%
% $ Description $
%   - raise_lackinput(funcname, nmin) raises an error message indicating
%     that the number of arguments input to the function specified by
%     funcname is not enough. (It should be at least nmin)
%
% $ History $
%   - Created by Dahua Lin on Nov 18th, 2005
%
error('sltoolbox:lackinput', ...
    'The number of input argument to %s should be at least %d.', ...
    funcname, nmin);