Description of sladdpath
Home > sltoolbox > utils > sladdpath.m
sladdpath
PURPOSE
SLADDPATH Adds dirpath to precede the filenames
SYNOPSIS
function paths = sladdpath(filenames, dirpath)
DESCRIPTION
SLADDPATH Adds dirpath to precede the filenames
 $ Syntax $
   - paths = sladdpath(filenames, dirpath)
 $ Arguments $
   - filenames:        the filenames without root path
   - dirpath:          the preceding dirpath to be added
   - paths:            the full names after the dirpath is added
 $ Description $
   - paths = sladdpath(filenames, dirpath) adds directory path in front
     of the filenames to form full paths.
 $ History $
   - Created by Dahua Lin, on Jul 27th, 2006
CROSS-REFERENCE INFORMATION
This function calls:
raise_lackinput RAISE_LACKINPUT Raises an error indicating lack of input argument
This function is called by:
edl_batchexp EDL_BATCHEXP Performs Batch experiments according to scheme
edl_go EDL_GO The Top interface for doing experiments in EDL
edl_readexpdefs EDL_READEXPDEFS Reads in an experiment definition from XML file
edl_readexpdefs_old EDL_READEXPDEFS Reads in experiment definition XML file
edl_writescript EDL_WRITESCRIPT Writes an EDL script
slpwcomp_blks SLPWCOMP_BLKS Computes pairwise value matrix
addfiles ADDFILES add a set of log files to the logger
isattached ISATTACHED Judges whether the file is attached to the logger
slmkdir SLMKDIR Makes a directory if it does not exist
slrmdir SLMKDIR Makes a directory if it does not exist
slpartitionpca_apply SLPARTITIONPCA_APPLY applies partition-based PCA to a set of arrays
slpartitionpca_construct SLPARTITIONPCA_CONSTRUCT Constructs the array from features
SUBFUNCTIONS
function pathstr = internal_addpath(filename, dirpath)
SOURCE CODE
function paths = sladdpath(filenames, dirpath)
%SLADDPATH Adds dirpath to precede the filenames
%
% $ Syntax $
%   - paths = sladdpath(filenames, dirpath)
%
% $ Arguments $
%   - filenames:        the filenames without root path
%   - dirpath:          the preceding dirpath to be added
%   - paths:            the full names after the dirpath is added
%
% $ Description $
%   - paths = sladdpath(filenames, dirpath) adds directory path in front
%     of the filenames to form full paths.
%
% $ History $
%   - Created by Dahua Lin, on Jul 27th, 2006
%
%% Parse and verify input arguments
if nargin < 2
    raise_lackinput('sladdpath', 2);
end
if iscell(filenames)
    ismulti = true;
elseif ischar(filenames)
    ismulti = false;
else
    error('sltoolbox:invalidarg', ...
        'The filenames should be either a single char string of the filename or a cell array of strings');
end
%% Main skeleton
if ~ismulti
    if ~isempty(dirpath)
        paths = internal_addpath(filenames, dirpath);
    else
        paths = filenames;
    end
else
    if ~isempty(dirpath)
        n = numel(filenames);
        paths = cell(size(filenames));
        for i = 1 : n
            paths{i} = internal_addpath(filenames{i}, dirpath);
        end
    else
        paths = filenames;
    end
end
%% Sub-functions
function pathstr = internal_addpath(filename, dirpath)
% precondition: dirpath is not empty
if dirpath(end) ~= '\'
    pathstr = [dirpath, '\', filename];
else
    pathstr = [dirpath, filename];
end