Description of slignorevars
Home > sltoolbox > utils > slignorevars.m
slignorevars
PURPOSE
SLIGNOREVARS Ignores the input variables
SYNOPSIS
function slignorevars(varargin)
DESCRIPTION
SLIGNOREVARS Ignores the input variables
 $ Syntax $
   - slignorevars(v1, v2, ...)
 $ Description $
   - slignorevars(v1, v2, ...) In high version of Matlab, the editor
     will produce a warning when it does not find the using of a
     defined variable. However, it is sometimes necessary for some
     designs. This function provides a way for you to plugin input
     variables, by this way, in your function, it will be apparent to
     editor that the variables are used.
 $ History $
   - Created by Dahua Lin, on Aug 14, 2006
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
slkmeans SLKMEANS Performs K-Means Clustering on samples
slkmeansex SLKMEANSEX Performs Generalized K-means
sllogdet SLLOGDET Computes the logarithm of determinant of a matrix in a robust way
slpwcomp_blks SLPWCOMP_BLKS Computes pairwise value matrix
slpweval SLPWEVAL Perform pairwise computation
slcountlines SLCOUNTLINES Count the lines of m-files in a folder and make a report
slpruneedgeset SLPRUNEEDGESET Prunes the edge set
slcumuscore SLCUMUSCORE Computes the cumulative score on multi-class classification
slgetroc SLGETROC Computes some point from ROC Curve
slcovlarge SLCOVLARGE Computes large covariance matrix using memory-efficient way
slfmm SLFMM Learns a Finite Mixture Model (FMM)
slgaussest SLGAUSSEST Estimates the Gaussian models from samples
slgmm SLGMM Learns Gaussian Mixture model from samples
slpca SLPCA Learns a PCA model from training samples
slpartitionpca SLPARTITIONPCA Performs Partition-based PCA and saves the models
sltensor_svd SLTENSOR_SVD Performs a Higher-Order SVD on a Tensor
SOURCE CODE
function slignorevars(varargin)
%SLIGNOREVARS Ignores the input variables
%
% $ Syntax $
%   - slignorevars(v1, v2, ...)
%
% $ Description $
%   - slignorevars(v1, v2, ...) In high version of Matlab, the editor
%     will produce a warning when it does not find the using of a
%     defined variable. However, it is sometimes necessary for some
%     designs. This function provides a way for you to plugin input
%     variables, by this way, in your function, it will be apparent to
%     editor that the variables are used.
%
% $ History $
%   - Created by Dahua Lin, on Aug 14, 2006
%