Description of slsharedisp_decindent
Home > sltoolbox > utils > slsharedisp_decindent.m
slsharedisp_decindent
PURPOSE
SLSHAREDISP_DECINDENT Decreases the indent of the displayer
SYNOPSIS
function slsharedisp_decindent(nsteps)
DESCRIPTION
SLSHAREDISP_DECINDENT Decreases the indent of the displayer
 $ Syntax $
   - slsharedisp_decindent()
   - slsharedisp_decindent(nsteps)
 $ Description $
   - slsharedisp_decindent() decreases the indent by one step.
   - slsharedisp_decindent(nsteps) decreases the indent by specified
     number of steps.
 $ History $
   - Created by Dahua Lin, on Aug 29, 2006
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
slkmeansex SLKMEANSEX Performs Generalized K-means
sliterproc SLITERPROC Runs a general iterative process
slfmm SLFMM Learns a Finite Mixture Model (FMM)
SOURCE CODE
function slsharedisp_decindent(nsteps)
%SLSHAREDISP_DECINDENT Decreases the indent of the displayer
%
% $ Syntax $
%   - slsharedisp_decindent()
%   - slsharedisp_decindent(nsteps)
%
% $ Description $
%   - slsharedisp_decindent() decreases the indent by one step.
%
%   - slsharedisp_decindent(nsteps) decreases the indent by specified
%     number of steps.
%
% $ History $
%   - Created by Dahua Lin, on Aug 29, 2006
%
global GLOBAL_SHARE_DISPLAYER;
if isempty(GLOBAL_SHARE_DISPLAYER)
    error('sltoolbox:gdisperr', ...
        'The global displayer is not open');
end
if nargin == 0
    nsteps = 1;
end
GLOBAL_SHARE_DISPLAYER(end).indent = ...
    GLOBAL_SHARE_DISPLAYER(end).indent - nsteps;