Description of slparseprops
Home > sltoolbox > utils > slparseprops.m
slparseprops
PURPOSE
SLPARSEPROPS Parses input parameters
SYNOPSIS
function P = slparseprops(P0, varargin)
DESCRIPTION
SLPARSEPROPS Parses input parameters
 $ Syntax $
   - P = slparseprops(P0, property_struct)
   - P = slparseprops(P0, property_name1, property_value1, ...)
 $ Syntax $
   - P = slparseprops(P0, property_struct) parses the properties from a
     property structure. The structure has multiple entries, with the
     property names as field names, and the property values are corresponding
     values.
   - P = slparseprops(P0, property_name1, property_value1, ...) parses
     the properties from property list. The list are a argument list with
     the form of multiple pairs of property names and corresponding values.
 $ Remarks $
   - The P0 specifies the default values of properties. All properties
     that can be set should appear in P0. If some properties specified in
     following arguments are not included in P0, an error will be raised.
   - Passing arguments in the way of property specification is a convenient
     method when multiple values need to be input. The user can only change
     some properties, while leaving others being in their default values.
     With this function, the function composer can design the function
     interfaces in the following form: func(main_parameters, varargin), and
     use parseprops(P0, varargin{:}) to parse the properties specified in the
     extra arguments.
 $ History $
   - Created by Dahua Lin on Dec 19th, 2005
   - Modified by Dahua Lin, on Aug 27, 2006
       - enhance the compatibility with older version of Matlab
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
edl_logerror EDL_LOGERROR Logs an error into logger
edl_readexpdefs EDL_READEXPDEFS Reads in an experiment definition from XML file
annsearch ANNSEARCH Approximate Nearest Neighbor Search
slkmeans SLKMEANS Performs K-Means Clustering on samples
slkmeansex SLKMEANSEX Performs Generalized K-means
slvechist SLVECHIST Makes the histogram on prototype vectors by voting
slvote SLVOTE Builds histogram by voting (or fuzzy voting)
sllog SLLOG Constructs a logger
slchangefilepart SLCHANGEFILEPART Changes some parts of the file path
sladjmat SLADJMAT Constructs the adjacency matrix representation of a graph
slaffinitymat SLAFFINITYMAT Constructs an affinity matrix
sledges2adjmat SLEDGES2ADJMAT Creates an adjacency matrix from edge set
slfindnn SLFINDNN Finds the nearest neighbors using specified strategy
slnngraph SLNNGRAPH Constructs a nearest neighborhood based graph
slpwgraph SLVALGRAPH Constructs a graph by computing values between nodes pairwisely
slpwmetricgraph SLPWMETRICGRAPH Constructs a graph based on pairwise metrics
slapplyfilterband SLAPPLYFILTERBAND Applies filter band to filter images in batch
slpixneighbors SLPIXNEIGHBORS Extracts the neighborhood of pixels from an image
slkernelfea SLKERNELFEA Extracts kernelized mapped features
slkfd SLKFD Perform Kernelized Fisher Discriminant Analysis
slkpca SLPCA Learns a Kernel PCA model from training samples
sliterproc SLITERPROC Runs a general iterative process
slproglearn SLPROGLEARN Performs Progressive Learning from sample source
slreevallearn SLREEVALLEARN Performs an iterative learning based on re-evaluation
slgembed SLGEMBED Solves the general graph-based embedding
slnbreconweights SLNBRECONWEIGHTS Solve the optimal reconstruction weights on given neighbors
sllinreg SLLINREG Performs Multivariate Linear Regression and Ridge Regression
sllogistreg SLLOGISTREG Performs Multivariate Logistic Regression
slfmm SLFMM Learns a Finite Mixture Model (FMM)
slgausscomb SLGAUSSCOMB Collects the means and variances/covariances to form GS
slgaussest SLGAUSSEST Estimates the Gaussian models from samples
slgausspdf SLGAUSSPDF Computes the probability density of Gaussian models
slgmm SLGMM Learns Gaussian Mixture model from samples
slregcov SLREGCOV Regularizes covariance matrices
slwhiten_from_samples SLWHITEN_FROM_SAMPLES Compute the whitening matrix from sample matrix
slcopca SLCOPCA Performs Coupled PCA Learning
sldlda SLDLDA Performs Direct Linear Discriminant Analysis
slfld SLFLD Performs Fisher Linear Discriminant Analysis
slgbfe SLGBFE Performs Graph-based Feature Extraction Learning
sllda SLLDA Trains a Linear Discriminant Model using specified method
slnlda SLNLDA Performs Nullspace-based Linear Discriminant Analysis
slpca SLPCA Learns a PCA model from training samples
slscatter SLSCATTER Compute the scatter matrix
sl2dpcaex SL2DPCAEX Learns Extended 2D PCA on a set of matrix samples
slarrmean SLARRMEAN Computes the mean of a set of arrays
slpartitionpca SLPARTITIONPCA Performs Partition-based PCA and saves the models
slcompresstext SLCOMPRESSTEXT Compresses a cell array of text
slclassify SLCLASSIFY Classifies a set of samples according to final scores
slclassify_blks SLCLASSIFY_BLKS Classifies samples according to blockwise scores
slsharedisp_attach SLSHAREDISP_ATTACH Attachs to global display options
xml_getattribs XML_GETATTRIBS Constructs an attribte struct from an XML element
SUBFUNCTIONS
function P = parse_props_from_struct(P0, S)
function P = parse_props_from_arglist(P0, args)
function check_names(P0, names)
SOURCE CODE
function P = slparseprops(P0, varargin)
%SLPARSEPROPS Parses input parameters
%
% $ Syntax $
%   - P = slparseprops(P0, property_struct)
%   - P = slparseprops(P0, property_name1, property_value1, ...)
%
% $ Syntax $
%   - P = slparseprops(P0, property_struct) parses the properties from a
%     property structure. The structure has multiple entries, with the
%     property names as field names, and the property values are corresponding
%     values.
%
%   - P = slparseprops(P0, property_name1, property_value1, ...) parses
%     the properties from property list. The list are a argument list with
%     the form of multiple pairs of property names and corresponding values.
%
% $ Remarks $
%   - The P0 specifies the default values of properties. All properties
%     that can be set should appear in P0. If some properties specified in
%     following arguments are not included in P0, an error will be raised.
%
%   - Passing arguments in the way of property specification is a convenient
%     method when multiple values need to be input. The user can only change
%     some properties, while leaving others being in their default values.
%     With this function, the function composer can design the function
%     interfaces in the following form: func(main_parameters, varargin), and
%     use parseprops(P0, varargin{:}) to parse the properties specified in the
%     extra arguments.
%
% $ History $
%   - Created by Dahua Lin on Dec 19th, 2005
%   - Modified by Dahua Lin, on Aug 27, 2006
%       - enhance the compatibility with older version of Matlab
%
if nargin == 1
    P = P0;
elseif nargin == 2
    if isempty(varargin{1})
        P = P0;
    elseif isstruct(varargin{1})
        P = parse_props_from_struct(P0, varargin{1});
    else
        error('sltoolbox:invalidarg', ...
            'Invalid input arguments for properties specification');
    end
else
    n = length(varargin);
    nitems = n / 2;
    if nitems ~= floor(nitems)  % not an integer
        error('sltoolbox:invalidarg', ...
            'Invalid input arguments for properties specification');
    end
    args = reshape(varargin, [2, nitems]);
    P = parse_props_from_arglist(P0, args);
end
%%------------ parse functions  -----------------
function P = parse_props_from_struct(P0, S)
s_names = fieldnames(S);
check_names(P0, s_names);
n = length(s_names);
P = P0;
for i = 1 : n
    curname = s_names{i};
    P.(curname) = S.(curname);
end
function P = parse_props_from_arglist(P0, args)
a_names = args(1, :);
check_names(P0, a_names);
n = length(a_names);
P = P0;
for i = 1 : n
    curname = a_names{i};
    P.(curname) = args{2, i};
end
function check_names(P0, names)
n = length(names);
for i = 1 : n
    if ~ischar(names{i})
        error('Encounter a non-char property name');
    end
end
for i = 1 : n
    if ~isfield(P0, names{i})
        error('The property name %s is invalid', names{i});
    end
end