Description of slsharedisp_detach
Home > sltoolbox > utils > slsharedisp_detach.m
slsharedisp_detach
PURPOSE
SLSHAREDISP_DETACH Detachs current function from global display
SYNOPSIS
function slsharedisp_detach()
DESCRIPTION
SLSHAREDISP_DETACH Detachs current function from global display
 $ Syntax $
   - slsharedisp_detach()
 $ History $
   - Created by Dahua Lin, on Aug 29, 2006
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
slkmeansex SLKMEANSEX Performs Generalized K-means
sliterproc SLITERPROC Runs a general iterative process
slproglearn SLPROGLEARN Performs Progressive Learning from sample source
slreevallearn SLREEVALLEARN Performs an iterative learning based on re-evaluation
slfmm SLFMM Learns a Finite Mixture Model (FMM)
SOURCE CODE
function slsharedisp_detach()
%SLSHAREDISP_DETACH Detachs current function from global display
%
% $ Syntax $
%   - slsharedisp_detach()
%
% $ History $
%   - Created by Dahua Lin, on Aug 29, 2006
%
global GLOBAL_SHARE_DISPLAYER;
if ~isempty(GLOBAL_SHARE_DISPLAYER)
    if length(GLOBAL_SHARE_DISPLAYER) == 1
        GLOBAL_SHARE_DISPLAYER = [];
    else
        GLOBAL_SHARE_DISPLAYER(end) = [];
    end
end