Description of disp
Home > sltoolbox > ExpDL > @dataset > disp.m
disp
PURPOSE
DISP displays the dataset fields
SYNOPSIS
function disp(DS)
DESCRIPTION
DISP displays the dataset fields
CROSS-REFERENCE INFORMATION
This function calls:
disp DISP displays the dataset fields
This function is called by:
disp DISP displays the dataset fields
display DISPLAY displays the dataset fields.
write WRITE Writes message to a logger
writeblank WRITEBLANK Writes a blank line to log
slbenchmark_batchfilter SLBENCHMARK_BATCHFILTER Compares the efficiency of batch filter
install_paths THE SCRIPT to install the sltoolbox paths to matlab system
sl2dpcaex SL2DPCAEX Learns Extended 2D PCA on a set of matrix samples
slpartitionpca SLPARTITIONPCA Performs Partition-based PCA and saves the models
slshowtext SLSHOWTEXT Displays the text
slsharedisp SLSHAREDISP Displays message using a shared configuration
SOURCE CODE
function disp(DS)
%DISP displays the dataset fields
disp(' [dataset object]');
disp(struct(DS))